services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('punkt')" && python train_model.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
